#!/usr/bin/env bash
set -euo pipefail

#####################################################################
# ~/dotfiles/install.sh
#
# Symlinks config into place, driven entirely by the `link` lines in
# deps.conf. Safe to re-run — skips correct links, backs up anything
# it would overwrite to ~/.dotfiles_backup/<timestamp>/.
#
# Symlinks ONLY. No packages, no sudo, no network — which makes this
# the right entry point on a locked-down machine where you can't
# install anything but still want your config.
#
# Usage:
#   ./install.sh              # every section in deps.conf
#   ./install.sh bash         # one section
#   ./install.sh bash nvim    # several
#
# Tool installation is `make install` — see `make help`.
#####################################################################

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_DIR="$HOME/.dotfiles_backup/$(date +%Y%m%d_%H%M%S)"

# shellcheck source=lib/manifest.sh
source "$DOTFILES_DIR/lib/manifest.sh"

case "$(uname -s)" in
  Darwin) _OS=mac ;;
  *)      _OS=linux ;;
esac

SECTIONS=("$@")
if [[ ${#SECTIONS[@]} -gt 0 ]]; then
  manifest_validate_sections "${SECTIONS[@]}"
fi

# --- Helpers -------------------------------------------------------

link_file() {
  local src="$1"
  local dest="$2"

  if [[ -L "$dest" && "$(readlink "$dest")" == "$src" ]]; then
    echo "  ok $dest"
    return
  fi

  if [[ -e "$dest" || -L "$dest" ]]; then
    mkdir -p "$BACKUP_DIR"
    mv "$dest" "$BACKUP_DIR/"
    echo "  backed up $dest -> $BACKUP_DIR/"
  fi

  mkdir -p "$(dirname "$dest")"
  ln -s "$src" "$dest"
  echo "  linked $dest -> $src"
}

echo ""
echo "Linking dotfiles from $DOTFILES_DIR ($_OS)"
if [[ ${#SECTIONS[@]} -gt 0 ]]; then
  echo "Sections: ${SECTIONS[*]}"
else
  echo "Sections: $(manifest_sections | tr '\n' ' ')"
fi
echo "-------------------------------------------"

# --- Walk the manifest's link lines --------------------------------

current=""
linked_any=0
while IFS=$'\t' read -r section src dest; do
  [[ -z "$section" ]] && continue
  if [[ "$section" != "$current" ]]; then
    current="$section"
    echo ""
    echo "[$section]"
  fi
  link_file "$DOTFILES_DIR/$src" "$dest"
  linked_any=1
done < <(manifest_lines link ${SECTIONS[@]+"${SECTIONS[@]}"})

[[ $linked_any -eq 0 ]] && echo "  (nothing to link)"

# --- Login shell shim (.bash_profile) ------------------------------
#
# Login shells (macOS Terminal/iTerm2, SSH on Linux/RHEL) read
# ~/.bash_profile instead of ~/.bashrc. This shim ensures .bashrc is
# always loaded regardless of shell mode. Generated rather than tracked
# because it's boilerplate, and only relevant when bash is being linked.

if [[ ${#SECTIONS[@]} -eq 0 ]] || printf '%s\n' "${SECTIONS[@]}" | grep -qx bash; then
  echo ""
  echo "[bash] login shell shim:"

  local_bash_profile="$DOTFILES_DIR/bash/bash_profile"
  if [[ ! -f "$local_bash_profile" ]]; then
    cat > "$local_bash_profile" <<'SHIM'
# ~/.bash_profile — login shell shim
# Source .bashrc so interactive login shells get the full config.
# Generated by dotfiles/install.sh
[[ -f ~/.bashrc ]] && source ~/.bashrc
SHIM
    echo "  created $local_bash_profile"
  fi
  link_file "$local_bash_profile" "$HOME/.bash_profile"
fi

# --- Summary -------------------------------------------------------

echo ""
echo "-------------------------------------------"

if [[ -d "$BACKUP_DIR" ]]; then
  echo "Backed up existing files to: $BACKUP_DIR"
fi

if [[ "$_OS" == "mac" ]]; then
  current_shell="$(dscl . -read /Users/"$USER" UserShell 2>/dev/null | awk '{print $2}')"
  if [[ "$current_shell" != *bash* ]]; then
    echo ""
    echo "NOTE: Your default shell is $current_shell"
    echo "  To switch to bash:  make shell   (or: chsh -s /bin/bash)"
  fi
fi

echo "Done! Restart your shell or run: reload"
echo ""
