#!/usr/bin/env bash
set -euo pipefail

#####################################################################
# ~/dotfiles/install.sh
#
# Symlinks dotfiles into place. Safe to re-run — skips existing links,
# backs up existing files. Works on both Linux (WSL) and macOS.
#
# Symlinks ONLY. No packages, no sudo, no network — which makes this
# the right entry point on a locked-down machine where you can't
# install anything but still want your config.
#
# Usage:
#   ./install.sh            # all areas (default)
#   ./install.sh bash       # bash config only
#   ./install.sh nvim       # nvim config only
#   ./install.sh bash nvim  # both, explicitly
#
# Tool installation lives elsewhere, per area:
#   bash/deps.sh · nvim/deps.sh · dev/deps.sh   (see `make help`)
#####################################################################

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_DIR="$HOME/.dotfiles_backup/$(date +%Y%m%d_%H%M%S)"

case "$(uname -s)" in
  Darwin) _OS=mac ;;
  *)      _OS=linux ;;
esac

# --- Area selection ------------------------------------------------

AREAS=("$@")
if [[ ${#AREAS[@]} -eq 0 ]]; then
  AREAS=(bash nvim)
fi

has_area() {
  local want="$1" a
  for a in "${AREAS[@]}"; do
    [[ "$a" == "$want" || "$a" == "all" ]] && return 0
  done
  return 1
}

for a in "${AREAS[@]}"; do
  case "$a" in
    bash|nvim|all) ;;
    *) echo "Unknown area: $a (expected: bash, nvim, all)"; exit 1 ;;
  esac
done

# --- Helpers -------------------------------------------------------

link_file() {
  local src="$1"
  local dest="$2"

  if [[ -L "$dest" && "$(readlink "$dest")" == "$src" ]]; then
    echo "  ok $dest"
    return
  fi

  if [[ -e "$dest" || -L "$dest" ]]; then
    mkdir -p "$BACKUP_DIR"
    mv "$dest" "$BACKUP_DIR/"
    echo "  backed up $dest -> $BACKUP_DIR/"
  fi

  mkdir -p "$(dirname "$dest")"
  ln -s "$src" "$dest"
  echo "  linked $dest -> $src"
}

echo ""
echo "Installing dotfiles from $DOTFILES_DIR ($_OS)"
echo "Areas: ${AREAS[*]}"
echo "-------------------------------------------"

# --- Bash config ---------------------------------------------------

if has_area bash; then
  echo ""
  echo "Bash:"

  link_file "$DOTFILES_DIR/bash/bashrc"                  "$HOME/.bashrc"
  link_file "$DOTFILES_DIR/bash/bash_roest_theme"        "$HOME/.bash_roest_theme"
  link_file "$DOTFILES_DIR/bash/bash_roest_productivity" "$HOME/.bash_roest_productivity"
  link_file "$DOTFILES_DIR/bash/bash_roest_git"          "$HOME/.bash_roest_git"
  link_file "$DOTFILES_DIR/bash/bash_roest_github"       "$HOME/.bash_roest_github"

  if [[ -f "$DOTFILES_DIR/bash/bash_roest_local" ]]; then
    link_file "$DOTFILES_DIR/bash/bash_roest_local" "$HOME/.bash_roest_local"
  fi
  if [[ -f "$DOTFILES_DIR/bash/bash_roest_password_commands" ]]; then
    link_file "$DOTFILES_DIR/bash/bash_roest_password_commands" "$HOME/.bash_roest_password_commands"
  fi

  # --- Login shell shim (.bash_profile) -----------------------------
  #
  # Login shells (macOS Terminal/iTerm2, SSH on Linux/RHEL) read
  # ~/.bash_profile instead of ~/.bashrc. This shim ensures .bashrc
  # is always loaded regardless of shell mode.

  echo ""
  echo "Login shell shim:"

  local_bash_profile="$DOTFILES_DIR/bash/bash_profile"
  if [[ ! -f "$local_bash_profile" ]]; then
    cat > "$local_bash_profile" <<'SHIM'
# ~/.bash_profile — login shell shim
# Source .bashrc so interactive login shells get the full config.
# Generated by dotfiles/install.sh
[[ -f ~/.bashrc ]] && source ~/.bashrc
SHIM
    echo "  created $local_bash_profile"
  fi
  link_file "$local_bash_profile" "$HOME/.bash_profile"
fi

# --- Nvim config ---------------------------------------------------
#
# The config directory itself is symlinked, so ~/.config/nvim is a link
# into this repo. bash_roest_nvim (n/nv/nvi) is linked here too, so those
# shortcuts exist only when the nvim area is installed.

if has_area nvim; then
  echo ""
  echo "Nvim:"

  link_file "$DOTFILES_DIR/nvim"                  "$HOME/.config/nvim"
  link_file "$DOTFILES_DIR/bash/bash_roest_nvim"  "$HOME/.bash_roest_nvim"
fi

# --- Git config ----------------------------------------------------

if has_area bash; then
  echo ""
  echo "Git:"

  if [[ -f "$DOTFILES_DIR/git/gitconfig" ]]; then
    link_file "$DOTFILES_DIR/git/gitconfig" "$HOME/.gitconfig"
  fi
fi

# --- Summary -------------------------------------------------------

echo ""
echo "-------------------------------------------"

if [[ -d "$BACKUP_DIR" ]]; then
  echo "Backed up existing files to: $BACKUP_DIR"
fi

if [[ "$_OS" == "mac" ]]; then
  current_shell="$(dscl . -read /Users/"$USER" UserShell 2>/dev/null | awk '{print $2}')"
  if [[ "$current_shell" != *bash* ]]; then
    echo ""
    echo "NOTE: Your default shell is $current_shell"
    echo "  To switch to bash:  make shell   (or: chsh -s /bin/bash)"
  fi
fi

echo "Done! Restart your shell or run: reload"
echo ""
