#!/usr/bin/env bash
set -euo pipefail

#####################################################################
# ~/dotfiles/install.sh
#
# Symlinks dotfiles into place. Safe to re-run — skips existing links,
# backs up existing files. Works on both Linux (WSL) and macOS.
#
# Usage:
#   git clone https://github.com/roest1/dotfiles.git ~/dotfiles
#   cd ~/dotfiles
#   make all        # or: ./install.sh
#####################################################################

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_DIR="$HOME/.dotfiles_backup/$(date +%Y%m%d_%H%M%S)"

case "$(uname -s)" in
  Darwin) _OS=mac ;;
  *)      _OS=linux ;;
esac

# --- Helpers -------------------------------------------------------

link_file() {
  local src="$1"
  local dest="$2"

  if [[ -L "$dest" && "$(readlink "$dest")" == "$src" ]]; then
    echo "  ok $dest"
    return
  fi

  if [[ -e "$dest" || -L "$dest" ]]; then
    mkdir -p "$BACKUP_DIR"
    mv "$dest" "$BACKUP_DIR/"
    echo "  backed up $dest -> $BACKUP_DIR/"
  fi

  mkdir -p "$(dirname "$dest")"
  ln -s "$src" "$dest"
  echo "  linked $dest -> $src"
}

echo ""
echo "Installing dotfiles from $DOTFILES_DIR ($_OS)"
echo "-------------------------------------------"

# --- Bash config ---------------------------------------------------

echo ""
echo "Bash:"

link_file "$DOTFILES_DIR/bash/bashrc"                  "$HOME/.bashrc"
link_file "$DOTFILES_DIR/bash/bash_roest_theme"        "$HOME/.bash_roest_theme"
link_file "$DOTFILES_DIR/bash/bash_roest_productivity" "$HOME/.bash_roest_productivity"
link_file "$DOTFILES_DIR/bash/bash_roest_git"          "$HOME/.bash_roest_git"
link_file "$DOTFILES_DIR/bash/bash_roest_github"       "$HOME/.bash_roest_github"

if [[ -f "$DOTFILES_DIR/bash/bash_roest_local" ]]; then
  link_file "$DOTFILES_DIR/bash/bash_roest_local" "$HOME/.bash_roest_local"
fi
if [[ -f "$DOTFILES_DIR/bash/bash_roest_password_commands" ]]; then
  link_file "$DOTFILES_DIR/bash/bash_roest_password_commands" "$HOME/.bash_roest_password_commands"
fi

# --- Login shell shim (.bash_profile) ---------------------------------
#
# Login shells (macOS Terminal/iTerm2, SSH on Linux/RHEL) read
# ~/.bash_profile instead of ~/.bashrc. This shim ensures .bashrc
# is always loaded regardless of shell mode.

echo ""
echo "Login shell shim:"

local_bash_profile="$DOTFILES_DIR/bash/bash_profile"
if [[ ! -f "$local_bash_profile" ]]; then
  cat > "$local_bash_profile" <<'SHIM'
# ~/.bash_profile — login shell shim
# Source .bashrc so interactive login shells get the full config.
# Generated by dotfiles/install.sh
[[ -f ~/.bashrc ]] && source ~/.bashrc
SHIM
  echo "  created $local_bash_profile"
fi
link_file "$local_bash_profile" "$HOME/.bash_profile"

# --- Neovim config -------------------------------------------------

echo ""
echo "Neovim:"

if [[ -d "$HOME/.config/nvim/.git" ]]; then
  echo "  ok ~/.config/nvim (separate git repo, skipping)"
else
  link_file "$DOTFILES_DIR/nvim" "$HOME/.config/nvim"
fi

# --- Git config ----------------------------------------------------

echo ""
echo "Git:"

if [[ -f "$DOTFILES_DIR/git/gitconfig" ]]; then
  link_file "$DOTFILES_DIR/git/gitconfig" "$HOME/.gitconfig"
fi

# --- Summary -------------------------------------------------------

echo ""
echo "-------------------------------------------"

if [[ -d "$BACKUP_DIR" ]]; then
  echo "Backed up existing files to: $BACKUP_DIR"
fi

if [[ "$_OS" == "mac" ]]; then
  current_shell="$(dscl . -read /Users/"$USER" UserShell 2>/dev/null | awk '{print $2}')"
  if [[ "$current_shell" != *bash* ]]; then
    echo ""
    echo "NOTE: Your default shell is $current_shell"
    echo "  To switch to bash:  make shell   (or: chsh -s /bin/bash)"
  fi
fi

echo "Done! Restart your shell or run: reload"
echo ""
