#!/usr/bin/env bash
# Generate mise.toml from deps.conf.
#
# WHY THIS EXISTS
#
# deps.conf declares *what* to install and *which provider* may install it.
# It deliberately says nothing about versions — a version column on every line
# would be noise on the dozen tools that come from apt or dnf, where the distro
# picks the version and that is the whole point of using it.
#
# But the mise-provided tools had no version anywhere. lib/pkg.sh ran
# `mise use -g "$tool@latest"`, and the resolved version landed in
# ~/.config/mise/config.toml — untracked, machine-local, outside the repo. Two
# machines provisioned a month apart got different software and nothing here
# recorded it, while CLAUDE.md claimed versions were pinned.
#
# So: deps.conf stays the single source of truth for the tool *set*, this
# script derives mise.toml from it, and `mise lock` turns that into mise.lock
# with per-platform checksums. Exactly the bun.lock / yarn.lock arrangement
# already used on the nvim side — one authored file, one generated file, and
# CI asserting they agree.
#
# mise.toml is GENERATED. Do not hand-edit the tool list; add or remove the
# tool in deps.conf and re-run `make mise-lock`. Versions ARE yours to edit:
# an existing pin is always preserved, and only new tools get resolved to the
# current latest.
#
#   ./tools/gen-mise.sh          write mise.toml
#   ./tools/gen-mise.sh --check  exit 1 if it would differ (used by CI)

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
OUT="$ROOT/mise.toml"

# shellcheck source=../lib/manifest.sh
source "$ROOT/lib/manifest.sh"

# Existing pin for a tool, if mise.toml already has one. Preserving these is
# what makes the generator safe to re-run: regenerating must never silently
# bump a version you deliberately chose.
existing_pin() {
  local tool="$1" version
  [[ -f "$OUT" ]] || return 1
  version="$(sed -n "s/^${tool} = \"\\(.*\\)\"\$/\\1/p" "$OUT" | head -1)"
  [[ -n "$version" ]] || return 1
  echo "$version"
}

# mise's registry name is not reliably either field of a deps.conf tool line.
# `nvim neovim` is `neovim` to mise (the package field), but
# `tree-sitter tree-sitter-cli` is `tree-sitter` (the command) — tree-sitter-cli
# is what cargo and dnf call it, and mise has no such entry. Asking the registry
# is the only correct answer; guessing a field is how the existing
# `mise use -g tree-sitter-cli` in lib/pkg.sh silently never worked.
mise_name() {
  local cmd="$1" pkg="$2" candidate
  for candidate in "${pkg:-$cmd}" "$cmd"; do
    [[ -z "$candidate" ]] && continue
    if mise latest "$candidate" >/dev/null 2>&1; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

mise_tools() {
  # A tool belongs here if `mise` appears anywhere in its provider chain —
  # including as a last resort (`pkg||cargo||mise`). If mise ends up being the
  # one that installs it, the version should be pinned regardless of where in
  # the chain it sat.
  while IFS=$'\t' read -r _section provider cmd pkg; do
    [[ ",${provider//||/,}," == *",mise,"* ]] || continue
    mise_name "$cmd" "$pkg" || echo "  ! mise has no registry entry for '${pkg:-$cmd}' — skipping" >&2
  done < <(manifest_lines tool) | sort -u
}

# Highest version mise has actually installed, ignoring entries it reports as
# missing. Preferred over `mise latest` because it records the state this
# machine is known to work in — and because `latest` is not even monotonic:
# qsv 22.0.1 was installed from `@latest`, while the registry currently reports
# 21.1.0 as latest. Pinning to a resolved-today value would have been a silent
# downgrade of a working tool.
installed_version() {
  local tool="$1"
  mise ls "$tool" 2>/dev/null \
    | grep -v missing \
    | awk '{print $2}' \
    | grep -E '^[0-9]' \
    | sort -V | tail -1
}

generate() {
  local tool version
  {
    echo "# @generated by tools/gen-mise.sh from deps.conf — do not edit the tool list."
    echo "#"
    echo "# Add or remove tools in deps.conf, then run: make mise-lock"
    echo "# Versions here are yours to change; regenerating preserves them."
    echo "# Checksums and per-platform URLs live in mise.lock."
    echo ""
    echo "[tools]"
    while read -r tool; do
      [[ -z "$tool" ]] && continue
      # Order matters: a pin you chose, then what this machine actually runs,
      # then the registry's current latest for a tool nobody has installed yet.
      version="$(existing_pin "$tool" || true)"
      [[ -n "$version" ]] || version="$(installed_version "$tool")"
      [[ -n "$version" ]] || version="$(mise latest "$tool" 2>/dev/null || true)"
      if [[ -z "$version" ]]; then
        echo "  ! could not resolve a version for '$tool' — skipping" >&2
        continue
      fi
      printf '%s = "%s"\n' "$tool" "$version"
    done < <(mise_tools)
  }
}

if [[ "${1:-}" == "--check" ]]; then
  # Deliberately registry-free, so this runs on a CI box with no mise: it
  # compares the tool SET both ways without asking mise to resolve anything.
  # Versions are not compared — a bump is a legitimate committed change, while
  # a tool in one file and not the other means the two have drifted apart.
  [[ -f "$OUT" ]] || { echo "mise.toml is missing — run: make mise-lock" >&2; exit 1; }

  pinned="$(sed -n 's/^\([A-Za-z0-9_.@/-]*\) = ".*"$/\1/p' "$OUT" | sort -u)"
  bad=0

  # Every mise-capable tool in deps.conf is pinned under one of its two names.
  while IFS=$'\t' read -r _section provider cmd pkg; do
    [[ ",${provider//||/,}," == *",mise,"* ]] || continue
    if ! echo "$pinned" | grep -qxE "$(printf '%s|%s' "${pkg:-$cmd}" "$cmd")"; then
      echo "deps.conf declares mise for '$cmd' but mise.toml pins no such tool" >&2
      bad=1
    fi
  done < <(manifest_lines tool)

  # ...and nothing is pinned that deps.conf no longer declares.
  declared="$(while IFS=$'\t' read -r _s provider cmd pkg; do
      [[ ",${provider//||/,}," == *",mise,"* ]] || continue
      echo "${pkg:-$cmd}"; echo "$cmd"
    done < <(manifest_lines tool) | sort -u)"
  while read -r tool; do
    [[ -z "$tool" ]] && continue
    echo "$declared" | grep -qx "$tool" || {
      echo "mise.toml pins '$tool', which deps.conf no longer declares" >&2; bad=1; }
  done <<<"$pinned"

  [[ $bad -eq 0 ]] || { echo "run: make mise-lock" >&2; exit 1; }
  echo "mise.toml matches deps.conf"

  # The lockfile is the point of the exercise; an unpinned tool set with no
  # checksums is the state this replaced.
  [[ -f "$ROOT/mise.lock" ]] || { echo "mise.lock is missing — run: make mise-lock" >&2; exit 1; }
  echo "mise.lock present"
  exit 0
fi

command -v mise >/dev/null 2>&1 || {
  echo "mise is not installed — cannot resolve versions" >&2
  exit 1
}

generate > "$OUT.tmp" && mv "$OUT.tmp" "$OUT"
echo "wrote $OUT"
