#!/usr/bin/env bash
set -euo pipefail

#####################################################################
# The one definition of what this repo lints, and how strictly.
#
#   ./tools/lint.sh              every shell source in the repo
#   ./tools/lint.sh a.sh b.sh    only those, ignoring anything that
#                                isn't one of ours
#
# Both callers go through here so the set cannot drift:
#
#   .githooks/pre-commit   passes the staged files, for fast feedback
#   .github/workflows/ci   passes nothing, so it sweeps the whole tree
#
# That split is deliberate and the two are not redundant. The hook is a
# convenience — it is skippable with `git commit --no-verify`, absent
# until install.sh has run once, and never runs at all for a commit made
# through GitHub's web UI. CI is the authority, and it is also the only
# one that catches a file nobody touched failing because shellcheck
# itself gained a rule.
#
# Missing shellcheck is an ERROR here, not a skip: this is the strict
# path. The hook does its own `command -v` first, which is where the
# graceful degradation belongs.
#####################################################################

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SEVERITY=warning

# Globs rather than a written-out list, for the same reason the Makefile
# globs sections: a new lib/*.sh, or a new section's deps.sh, is covered
# the moment it exists instead of when someone remembers to add it.
#
# bash/* is in scope even though those files are sourced rather than
# executed. It was the largest unlinted surface in the repo — the
# machinery was linted while the ~2,700 lines it exists to install were
# not — and it found a `cd` that could fail silently in mkcd, an
# `export JAVA_HOME=$(...)` that masked its own failure, and a dead jq
# subprocess running on every log view.
#
# bash/bash_profile is generated by install.sh when absent. The heredoc
# there is kept byte-identical to the tracked file, so this cannot pass
# in the repo and fail on a machine that regenerated it.
PATTERNS=(
  bootstrap.sh
  install.sh
  bash/bashrc
  'bash/bash_*'
  'lib/*.sh'
  '*/deps.sh'
  'tools/*.sh'
  .githooks/pre-commit
)

# Is this path one of ours? Used for the caller-supplied list, where the
# input is "everything staged" and most of it is markdown and YAML.
__lintable() {
  local path="$1" glob
  for glob in "${PATTERNS[@]}"; do
    # Unquoted on purpose — the right-hand side is a pattern, not a string.
    # shellcheck disable=SC2053
    [[ "$path" == $glob ]] && return 0
  done
  return 1
}

files=()

if (( $# )); then
  for f in "$@"; do
    # -f because a caller may hand us a path that no longer exists.
    [[ -f "$f" ]] && __lintable "$f" && files+=("$f")
  done
else
  shopt -s nullglob
  for glob in "${PATTERNS[@]}"; do
    # Deliberate glob expansion; nullglob drops patterns that match nothing.
    # shellcheck disable=SC2206
    files+=($glob)
  done
  shopt -u nullglob
fi

# Nothing shell-shaped in this commit is a pass, not an error.
(( ${#files[@]} )) || exit 0

if ! command -v shellcheck >/dev/null 2>&1; then
  echo "lint: shellcheck not found." >&2
  echo "  Declared in deps.conf; install it with: make install bash" >&2
  exit 1
fi

# A file can match two patterns once the globs overlap, and shellcheck
# would then report the same finding twice.
IFS=$'\n' read -r -d '' -a files < <(printf '%s\n' "${files[@]}" | sort -u && printf '\0')

exec shellcheck --severity="$SEVERITY" "${files[@]}"
